### ISSUE TITLE
The file cannot be found when the most execution is finished在执行快结束是报错找不到文件ret.npy

### ISSUE THREAD

**Issue by xhb951120474** [OmarPadierna/3DReconstruction#4]
Traceback (most recent call last):
  File "D:/shiyanwenjian/3DReconstruction-master/Calibration/calibrate.py", line 71, in <module>
    np.save("./camera_params/ret", ret)
  File "<__array_function__ internals>", line 6, in save
  File "D:\Python\Python37\lib\site-packages\numpy\lib\npyio.py", line 541, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './camera_params/ret.npy'
报错如上所示

**Comment by xhb951120474** [comment]
Can the author help me to solve this problem

**Comment by huzhoudiao** [comment]
老哥，你者就是文件路径错了，改一下就可以了

**Comment by OmarPadierna** [comment]
Its probably because the directory /camera_params/ does not exist. You should create that directory in the same folder where you have calibrate.py. That is, in your folder called /Calibration/ create a new folder called camera_params and then run the script again.
